### ISSUE TITLE
Support menu for mobile devices

### ISSUE THREAD

**Issue by santoshyadavdev** [santoshyadavdev/angular-snippets#25]
**Is your feature request related to a problem? Please describe.**

The Menu is not responsive and breaks in mobile view

**Describe the solution you'd like**

https://github.com/lancerossdev/nofuss contains an example of mobile menu 

**Describe alternatives you've considered**

**Additional context**

**Comment by olierxleben** [comment]
if I understand correct, you want to switch to a burger menu on small screen?

**Comment by santoshyadavdev** [comment]
Yes
